def public_pods
    
    source 'https://github.com/CocoaPods/Specs.git' # 公有源
    
end

def njspec_pods
    
    source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源
#    pod 'NJKit', :git => 'https://github.com/njhu/NJKit.git'
    pod 'NJKit'
    pod 'DYTrends', :path => '../'
    #pod 'NJKit', :path => '../../NJKit/'
    #pod 'DYIJKPlayerComponent', :git => 'git@mgit.dz11.com:douyu-ios/DYIJKPlayerComponent.git', :commit => '610ec07e465c19a83e9a41d7dacfaa55b4248750' #'0.1.4' # 播放器组件
    #pod 'DYDanmakuDebug', '2.8.8' , :configuration => 'Debug' # 弹幕库 debug
    #pod 'DYDanmaku', '2.8.8', :configuration => 'Release' # 弹幕库 release
    #pod 'DYGambleBusinessKit', :path => '../DYGambleBusinessKit/'
    #pod 'DYStarMagicBusinessKit','0.1.2'
    
end

platform :ios, '10.3'

use_frameworks!

target 'DYTrends_Example' do
    
    inhibit_all_warnings!
    
    njspec_pods
    
    public_pods
    
    pod 'DYTrends', :path => '../'
    
    target 'DYTrends_Tests' do
        inherit! :search_paths
        
        
    end
end
